### ISSUE TITLE
mismatch of lincense.

### ISSUE THREAD

**Issue by roxell** [linux-test-project/kirk#21]
In the LICENSE file its GPLv2
However, in setup.py it says LGPLv2. Assuming this is a copy-paste bug or?

**Comment by acerv** [comment]
Thanks for finding it out. Gonna fix it

**Comment by acerv** [comment]
Fixed by https://github.com/linux-test-project/kirk/commit/08fb2dc21e152648d6838d3b35a09fbf95bdb3c9
